---
action: Util.TextBlock
props:
  header: LiveView Installation Guide
  body: |
    While Phoenix LiveView is under heavy development, the installation
    instructions are likely to change rapidly as well. The instructions below
    will serve if you are installing the latest stable version from Hex. If you
    are installing from GitHub to get the latest features, follow the
    instructions in [the README there][1] instead.

    [1]: https://github.com/phoenixframework/phoenix_live_view/blob/master/README.md#installation
children:
  - playbook: live_view_body.yaml 
