---
- action: Util.TextBlock
  params:
    header: HEADERn
    body: BODYn
  children:
    - action: Util.TextBlock
      params:
        header: HEADER11
        body: BODY11
      children:
        - action: Util.TextBlock
          params:
            header: HEADER111
            body: BODY111
          children:
            - action: Util.TextBlock
              params:
                header: HEADER1111
                body: BODY1111
    - action: Util.TextBlock
      params:
        header: HEADER22
        body: BODY22
      children:
        - action: Util.TextBlock
          params:
            header: HEADER222
            body: BODY222
          children:
            - action: Util.TextBlock
              params:
                header: HEADER2222
                body: BODY2222
